beacon:
    type: rest
    resource: BeaconBundle\Controller\BeaconController
    prefix: /v1/
locale:
    type: rest
    resource: BeaconBundle\Controller\LocaleController
    prefix: /v1/
security:
    resource: BeaconBundle\Controller\SecurityController
    prefix: /v1/